"""make manufacturer_id description catalog_url nullable

Revision ID: 330c45679a59
Revises: ad0007e185bf
Create Date: 2024-12-15 22:06:45.745505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '330c45679a59'
down_revision: Union[str, None] = 'ad0007e185bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'manufacturer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'manufacturer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
