"""add_drawing_id_to_image

Revision ID: 58eb0c0b35f1
Revises: 41a26573eff9
Create Date: 2025-01-18 22:53:38.048519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58eb0c0b35f1'
down_revision: Union[str, None] = '41a26573eff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # まずdrawingsテーブルを作成
    op.create_table(
        'drawings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('property_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True),
                  server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(
            ['property_id'], ['properties.id'], name='drawings_property_id_fkey')
    )

    # 次にimagesテーブルにdrawing_idカラムを追加
    op.add_column('images', sa.Column(
        'drawing_id', sa.Integer(), nullable=True))

    # 最後に外部キー制約を追加
    op.create_foreign_key(
        'fk_images_drawing_id',
        'images',
        'drawings',
        ['drawing_id'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # まず外部キー制約を削除
    op.drop_constraint('fk_images_drawing_id', 'images', type_='foreignkey')

    # 次にdrawing_idカラムを削除
    op.drop_column('images', 'drawing_id')

    # 最後にdrawingsテーブルを削除
    op.drop_table('drawings')
    # ### end Alembic commands ###
