"""remove property relationships

Revision ID: 66e3b267e6bb
Revises: e69aa9ed894c
Create Date: 2024-12-15 22:26:10.403811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e3b267e6bb'
down_revision: Union[str, None] = 'e69aa9ed894c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
