"""add session_id to transactions

Revision ID: 8451c95f8759
Revises: c491d9aa903f
Create Date: 2024-01-05 21:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8451c95f8759'
down_revision: Union[str, None] = 'c491d9aa903f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column(
        'session_id', sa.String(), nullable=True))
    op.alter_column('transactions', 'payment_intent_id',
                    existing_type=sa.String(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'payment_intent_id',
                    existing_type=sa.String(),
                    nullable=False)
    op.drop_column('transactions', 'session_id')
    # ### end Alembic commands ###
