"""add s3_key to images

Revision ID: ad0007e185bf
Revises: 6b80b5c9d268
Create Date: 2024-12-15 13:58:55.934197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad0007e185bf'
down_revision: Union[str, None] = '6b80b5c9d268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('s3_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 's3_key')
    # ### end Alembic commands ###
