"""Make product_category_id and product_code optional in Product model

Revision ID: bc717bc76366
Revises: a339975b5ad2
Create Date: 2024-12-27 08:18:41.828149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc717bc76366'
down_revision: Union[str, None] = 'a339975b5ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'product_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'product_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'product_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'product_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
