"""replace_manufacturer_id_with_manufacturer_name

Revision ID: bf8f97379edf
Revises: c188816df799
Create Date: 2025-01-04 23:47:13.854771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf8f97379edf'
down_revision: Union[str, None] = 'c188816df799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add manufacturer_name column
    op.add_column('products', sa.Column(
        'manufacturer_name', sa.String(), nullable=True))

    # 2. Copy data from companies table to manufacturer_name
    op.execute("""
        UPDATE products p
        SET manufacturer_name = c.name
        FROM companies c
        WHERE p.manufacturer_id = c.id
    """)

    # 3. Drop foreign key constraint
    op.drop_constraint('products_manufacturer_id_fkey',
                       'products', type_='foreignkey')

    # 4. Drop manufacturer_id column
    op.drop_column('products', 'manufacturer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add manufacturer_id column
    op.add_column('products', sa.Column('manufacturer_id',
                  sa.INTEGER(), autoincrement=False, nullable=True))

    # 2. Add foreign key constraint
    op.create_foreign_key('products_manufacturer_id_fkey',
                          'products', 'companies', ['manufacturer_id'], ['id'])

    # 3. Drop manufacturer_name column
    op.drop_column('products', 'manufacturer_name')
    # ### end Alembic commands ###
