"""add charge_id and stripe_transfer_id to transactions

Revision ID: c491d9aa903f
Revises: bf8f97379edf
Create Date: 2024-01-05 12:11:25.830624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c491d9aa903f'
down_revision: Union[str, None] = 'bf8f97379edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column(
        'charge_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column(
        'stripe_transfer_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'stripe_transfer_id')
    op.drop_column('transactions', 'charge_id')
    # ### end Alembic commands ###
