"""add_stripe_capabilities_to_seller_profiles

Revision ID: c98fdc7057d4
Revises: bc717bc76366
Create Date: 2024-12-28 13:39:07.349708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98fdc7057d4'
down_revision: Union[str, None] = 'bc717bc76366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller_profiles', sa.Column('stripe_capabilities', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller_profiles', 'stripe_capabilities')
    # ### end Alembic commands ###
