"""create take rates table

Revision ID: d3a6ae95c286
Revises: 322cdd2f5627
Create Date: 2025-01-09 17:46:44.532734

"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a6ae95c286'
down_revision: Union[str, None] = '322cdd2f5627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    take_rates = op.create_table('take_rates',
                                 sa.Column('id', sa.Integer(), nullable=False),
                                 sa.Column('user_id', sa.Integer(),
                                           nullable=True),
                                 sa.Column('is_default', sa.Boolean(),
                                           nullable=False, default=False),
                                 sa.Column('take_rate', sa.Numeric(
                                     precision=5, scale=2), nullable=False),
                                 sa.Column('date_from', sa.DateTime(),
                                           nullable=False),
                                 sa.Column('date_to', sa.DateTime(),
                                           nullable=True),
                                 sa.Column('created_at',
                                           sa.DateTime(), nullable=False),
                                 sa.Column('updated_at',
                                           sa.DateTime(), nullable=False),
                                 sa.Column('created_by', sa.Integer(),
                                           nullable=False),
                                 sa.Column('note', sa.String(), nullable=True),
                                 sa.ForeignKeyConstraint(
                                     ['user_id'], ['users.id'], ),
                                 sa.ForeignKeyConstraint(
                                     ['created_by'], ['users.id'], ),
                                 sa.PrimaryKeyConstraint('id')
                                 )
    op.create_index(op.f('ix_take_rates_id'),
                    'take_rates', ['id'], unique=False)

    # デフォルトの手数料率（20%）を追加
    op.bulk_insert(
        take_rates,
        [
            {
                'user_id': 1,
                'is_default': True,
                'take_rate': 20.00,
                'date_from': datetime.utcnow(),
                'date_to': datetime(2099, 12, 31, 23, 59, 59),
                'created_at': datetime.utcnow(),
                'updated_at': datetime.utcnow(),
                'created_by': 1,  # システム管理者のID
                'note': 'デフォルトの手数料率（20%）'
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_take_rates_id'), table_name='take_rates')
    op.drop_table('take_rates')
    # ### end Alembic commands ###
