"""remove property_id from products

Revision ID: e69aa9ed894c
Revises: 330c45679a59
Create Date: 2024-12-15 22:22:33.656501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e69aa9ed894c'
down_revision: Union[str, None] = '330c45679a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_property_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'property_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('property_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('products_property_id_fkey', 'products', 'properties', ['property_id'], ['id'])
    # ### end Alembic commands ###
