"""add_status_to_property_room_product

Revision ID: f531b974fbd7
Revises: 58eb0c0b35f1
Create Date: 2024-01-18 23:53:38.048519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f531b974fbd7'
down_revision: Union[str, None] = '58eb0c0b35f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Propertiesテーブルにstatus列を追加
    op.add_column('properties', sa.Column('status', sa.String(),
                  nullable=False, server_default='default'))
    op.add_column('properties', sa.Column(
        'updated_at', sa.DateTime(timezone=True), nullable=True))

    # Roomsテーブルにstatus列とis_deleted列を追加
    op.add_column('rooms', sa.Column('status', sa.String(),
                  nullable=False, server_default='default'))
    op.add_column('rooms', sa.Column(
        'updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rooms', sa.Column('is_deleted', sa.Boolean(),
                  nullable=False, server_default='false'))

    # Productsテーブルにstatus列とis_deleted列を追加
    op.add_column('products', sa.Column('status', sa.String(),
                  nullable=False, server_default='default'))
    op.add_column('products', sa.Column(
        'updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(),
                  nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Productsテーブルから列を削除
    op.drop_column('products', 'is_deleted')
    op.drop_column('products', 'status')
    op.drop_column('products', 'updated_at')

    # Roomsテーブルから列を削除
    op.drop_column('rooms', 'is_deleted')
    op.drop_column('rooms', 'status')
    op.drop_column('rooms', 'updated_at')

    # Propertiesテーブルから列を削除
    op.drop_column('properties', 'status')
    op.drop_column('properties', 'updated_at')
    # ### end Alembic commands ###
